### ISSUE TITLE
Images with space in filename do not display in gallery

### ISSUE THREAD

**Issue by jessedewald** [contourlineprinter/capstone#4]
Images with filenames that have spaces (ex. "my picture.jpg") upload fine but don't render in gallery correctly. Filenames get truncated in the HTML. For example, "my picture.jpg" becomes "my.jpg", leading to broken image.

**Comment by kennysexton** [comment]
Added this line of code as part of the uploadImageServlet to take spaces out of files on upload :). 

 Reopen if there are any issues
```
// remove spaces, make lowercase
name = name.replaceAll(" ", "_"); 
```
