### ISSUE TITLE
SVG not printing to folders with spaces in between

### ISSUE THREAD

**Issue by yummiecrossiant** [contourlineprinter/capstone#6]
trying to print in server to a folder called "New folder" is not working. It's getting the right arguments but nothing appears.

**Comment by kennysexton** [comment]
Does it have 777 permissions?

**Comment by yummiecrossiant** [comment]
yea it does. i even tried root user. i thought i fixed it today but it's still like this. i'll work on it some more tonight.

**Comment by yummiecrossiant** [comment]
i think i fixed it. it seems to be working for svg relative and absolute paths. i'll leave this open for now since i haven't finish testing.

**Comment by yummiecrossiant** [comment]
it didn't work for the image argument as well so today i made a function (in parseArguments.py) that will parse through the arguments. it should be working now i hope lol. if anyone has a problem, let me know and i can try to fix it. closing this now.
